### ISSUE TITLE
BogoSort

### ISSUE THREAD

**Issue by cosane** [bozburak/Algorithms_In_Python#1]
Selamlar Burakcım,

Baştan itibaren kendin yazmaya giriştiğin için seni tebrik ederim. Elbette ilk girişimler nadiren hatasız sonuçlanır :)

1. Array ve array_two adında iki ayrı değişkene değer girmiş olman bence yanlış bir teknik. Değeri birine gir, öbürünü ona eşitle ;)
2. Sen dikkat edersen aslında quicksort yapıyorsun. Yani "quicksort ile ben kesin olarak bir dizeyim de, sonra rastgele dizimlerimi bu kesin dizili olanla karşılaştırayım" diyorsun ama o zaman bogonun anlamı kalmıyor. Bu bogo+quick oluyor.
3. Rastgele dizimlerini yanlış bir metot ile üretiyorsun. Dizinin tüm elemanlarını o dizinin boyutu aralığındaki rastgele sayılarla dolduruyor ve bunu quick ile karşılaştırıyorsun ama burada iki sorun var
   - 1- Dizinin elemanları aynı olabiliyor. "1,1,3" veya "2,3,2" gibi.
   - 2- Belki de sana verilen dizi 3 elemanlı ama "16,384,2" gibi "1,2,3"den çok daha farklı rakamlardan oluşacak. O zaman ne yapacaksın?

Bence bu BogoSort üzerine daha çok kafa yormalısın ;)

**Comment by cosane** [comment]
Ah burakcım ah! Ben bu yazıyı 3 gün önde yazmıştım ama daha şimdi farkettim ki göndermemişim, sekme öylece açık kalmış :(

**Comment by bozburak** [comment]
Boggo Sort kodlarını tekrar inceler misiniz?
sorter fonksiyonunu karşılaştırma yapmak için kullandım :)
ve yeni bir metodla hem aynı sayı gelme hemde kesirli sayılar içinde karıştırma yaptım.
